name: Carbonfix_env
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.4.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - ca-certificates=2024.8.30=h56e8100_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - console_shortcut=0.1.1=haa95532_6
  - debugpy=1.8.5=py38h2698bfa_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - importlib-metadata=8.4.0=pyha770c72_0
  - importlib_metadata=8.4.0=hd8ed1ab_0
  - ipykernel=6.29.5=pyh4bbf305_0
  - ipython=8.12.2=pyh08f2357_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=8.6.2=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py38haa244fe_0
  - krb5=1.21.3=hdf4eb48_0
  - libffi=3.4.4=hd77b12b_1
  - libsodium=1.0.18=h8d14728_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - openssl=3.3.1=h2466b09_3
  - packaging=24.1=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.2=py38haa95532_0
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - prompt-toolkit=3.0.47=pyha770c72_0
  - prompt_toolkit=3.0.47=hd8ed1ab_0
  - psutil=6.0.0=py38h4cb3324_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - python=3.8.19=h1aa4202_0
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pywin32=306=py38hd3f51b4_2
  - pyzmq=26.2.0=py38h3c56b06_0
  - setuptools=72.1.0=py38haa95532_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tornado=6.4.1=py38h4cb3324_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - ucrt=10.0.22621.0=h57928b3_0
  - vc=14.40=h2eaa2aa_0
  - vc14_runtime=14.40.33810=hcc2c482_20
  - vs2015_runtime=14.40.33810=h3bf8584_20
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.43.0=py38haa95532_0
  - zeromq=4.3.5=he1f189c_4
  - zipp=3.20.1=pyhd8ed1ab_0
  - pip:
      - comtypes==1.4.6
      - contourpy==1.1.1
      - cycler==0.12.1
      - et-xmlfile==2.0.0
      - fonttools==4.53.1
      - importlib-resources==6.4.4
      - kiwisolver==1.4.5
      - matplotlib==3.7.5
      - numpy==1.24.4
      - openpyxl==3.1.5
      - pandas==2.0.3
      - pillow==10.4.0
      - pyparsing==3.1.4
      - pytz==2024.1
      - pywinauto==0.6.8
      - scienceplots==2.1.1
      - seaborn==0.13.2
      - tzdata==2024.1
